#!bin/bash
bee=$JAVA_HOME/lib/bee-latest.jar
if [ ! -e $bee ]; then
    bee=bee-latest.jar
    if [ ! -e $bee ]; then
        echo $bee is not found localy, try to download it from network.
        curl -#L -o $bee https://jitpack.io/com/github/teletha/bee/latest/bee-latest.jar
    fi
fi
java -javaagent:$bee -cp $bee bee.Bee "$@"
