#!bin/bash
bee=bee.bin
if [ ! -e $bee ]; then
    bee=$JAVA_HOME/lib/bee-latest.jar
    if [ ! -e $bee ]; then
        echo $bee is not found locally, try to download it from network.
        curl -#L -o $bee https://jitpack.io/com/github/teletha/bee/latest/bee-latest.jar
    fi
fi
java -javaagent:$bee -cp $bee bee.Bee "$@"
