name: Build and Deploy

on:
  push:
    branches: [master, main, test-*]
  pull_request:
    branches: [master, main]
  workflow_dispatch:

env:
  JAVA_VERSION: '21'
  DISTRIBUTION: 'zulu'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:          
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up JDK
      uses: actions/setup-java@v4
      if: steps.cache-java.outputs.cache-hit != 'true'
      with:
        distribution: ${{ env.DISTRIBUTION }}
        java-version: ${{ env.JAVA_VERSION }}

    - name: Show java
      run: |
        echo $JAVA_HOME
        echo $PATH
        java -version
        cat /home/runner/.m2/settings.xml

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ${{ env.JAVA_HOME }}/lib/bee/repository
        key: ${{ runner.os }}-bee-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-bee

    - name: Build artifact and site
      run: |
        if [ -e "bee" ]; then
          source bee install doc:site maven:pom ci:readme ci:license
        else
          version=$(curl -SsL https://git.io/stable-bee)
          curl -SsL -o bee-${version}.jar https://jitpack.io/com/github/teletha/bee/${version}/bee-${version}.jar
          java -javaagent:bee-${version}.jar -cp bee-${version}.jar bee.Bee install doc:site maven:pom ci:readme ci:license
        fi

    - name: Deploy site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: target/site

    - name: Request Releasing
      uses: GoogleCloudPlatform/release-please-action@v4
      with:
        release-type: simple
        package-name: bee

    - name: Auto commit
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: update repository info
