name: Release Please

on:
  push:
    branches: [master, main]

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: java-bom
          package-name: bee
